import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] }); // Use Poppins

export const metadata: Metadata = {
  title: "Ridhwan Nashir Personal Website",
  description: "Generated by Ridhwan N",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
